# Generated by Django 5.1.5 on 2025-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies shows the alteraion or any change in the models
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
